### ISSUE TITLE
"no material file!" when loading hand_model/scene_spec.yml

### ISSUE THREAD

**Issue by xinghaochen** [jsupancic/libhand-public#1]
hello, I compiled this modified libhand successfully. However, when I execute the ./pose_designer and choose the scene spec file in hand_model/  , it outputs the following messages:

``` bash
WARNING: the mesh 'hand.mesh' includes vertices with more than 4 bone assignments. The lowest weighted assignments beyond this limit have been removed, so your animation may look slightly different. To eliminate this, reduce the number of bone assignments per vertex on your mesh to 4.
no material file!
DefaultWorkQueue('Root') shutting down.
```

Meanwhile, The "HandRenderer Window" display nothing.

I also tried the scene spec file in hand_model_no_arm/ and hand_model_new/, it didn't work and output the following messages:

``` bash
[DotSceneLoader] Parsing dotScene file with version 1.0.1
Mesh: Loading hand.mesh.
[DotSceneLoader] Error loading an entity!
no camera :-(
Destroying resource group 0HandRenderer Scene Resources
Unloading resource group 0HandRenderer Scene Resources
Finished unloading resource group 0HandRenderer Scene Resources
Exception: The scene does not have the object hand
DefaultWorkQueue('Root') shutting down.
Segmentation fault (core dumped)
```

Could you give some advise to help me to solve these problems? Thanks.

**Comment by jsupancic** [comment]
For hand_model_no_arm I get: 

```
[DotSceneLoader] Parsing dotScene file with version 1.0.1
Mesh: Loading hand.mesh.
Skeleton: Loading hand.skeleton
mesh file = hand.mesh
WARNING: the mesh 'hand.mesh' includes vertices with more than 4 bone assignments. The lowest weighted assignments beyond this limit have been removed, so your animation may look slightly different. To eliminate this, reduce the number of bone assignments per vertex on your mesh to 4.
Set material skin for hand
[DotSceneLoader] Error loading an entity!
no camera :-(
```

It looks like the exception handler in dot_sceneloader.cc:642 gets called for you but not me. 

I've pushed a change adding more verbose error reporting in that exception handler. Please pull the update, recompile and report the extended error output. Maybe, that will give us some clue as to why it doesn't work on your system.

Best wishes, James

**Comment by xinghaochen** [comment]
Similar problems and effective solutions can be found in  issues [#2](https://github.com/jsupancic/libhand-public/issues/2).

I will close this issue. Thanks.
